

@startuml Memor DBER

'groups two or more similar arrows together
skinparam groupInheritance 2

'Entities
entity User {
* UserID : int <<PK>> <<generated>>
--
* Email_Address : varchar
* Password : varchar
}

entity Account {
* AccountID : int <<PK>> <<generated>>
--
* UserID : int <<FK>>
* TransactionID : int <<FK>>
* Balance : decimal 

}

'Relationship-Based Entities


'Entity-Entity Arrows 
'Including: Composition, Aggregation, and Extension/Inheritance [superclass notation])



'Entity-Relationship Arrows 
'Entity --> Relationship


@enduml